name: WeatherForecast CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Base checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Access secrets
        env:
          APIKEY: ${{ secrets.APIKEY }}
          APIURL: ${{ secrets.APIURL }}
        run: echo -e "apiKey=$APIKEY\napiUrl=$APIURL"  > ./local.properties
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Give permission
        run: chmod +x gradlew    
      - name: Perform build
        run: ./gradlew build
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Access secrets
        env:
          APIKEY: ${{ secrets.APIKEY }}
          APIURL: ${{ secrets.APIURL }}
        run: echo -e "apiKey=$APIKEY\napiUrl=$APIURL"   > ./local.properties
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Give permission
        run: chmod +x gradlew  
      - name: Execute unit tests
        run: ./gradlew testDebugUnitTest
      - uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless  
